# Generated by Django 3.1.6 on 2021-03-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BAM',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('path', models.TextField()),
                ('file', models.FileField(default=None, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoverageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('cov_10x', models.IntegerField()),
                ('cov_20x', models.IntegerField()),
                ('cov_30x', models.IntegerField()),
                ('cov_40x', models.IntegerField()),
                ('cov_50x', models.IntegerField()),
                ('cov_100x', models.IntegerField()),
                ('cov_min', models.IntegerField()),
                ('cov_max', models.IntegerField()),
                ('cov_mean', models.FloatField()),
                ('cov_region', models.IntegerField()),
                ('pct_10x', models.IntegerField()),
                ('pct_20x', models.IntegerField()),
                ('pct_30x', models.IntegerField()),
                ('pct_40x', models.IntegerField()),
                ('pct_50x', models.IntegerField()),
                ('pct_100x', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcelReport',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('path', models.TextField()),
                ('file', models.FileField(default=None, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exon',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('hgnc_id', models.CharField(max_length=255)),
                ('hgnc_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenomeBuild',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenomicCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('chrom', models.CharField(max_length=2)),
                ('pos', models.IntegerField()),
                ('genome_build', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.genomebuild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineVersion',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=255)),
                ('pipeline', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.pipeline')),
                ('updates', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='updated_by', to='db.pipelineversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('worksheet', models.CharField(max_length=255)),
                ('command_line_usage', models.CharField(max_length=255)),
                ('completed_at', models.DateTimeField()),
                ('output_dir', models.CharField(max_length=255)),
                ('fastq_dir', models.CharField(max_length=255)),
                ('interop_dir', models.CharField(max_length=255)),
                ('qc_status', models.IntegerField(choices=[
                 (0, 'Pending'), (1, 'Pass'), (2, 'Fail')], default=1)),
                ('pipeline_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                       related_name='pipeline_version', to='db.pipelineversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('sample_id', models.CharField(max_length=50)),
                ('lab_no', models.CharField(max_length=50)),
                ('index', models.CharField(max_length=50)),
                ('index2', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Samplesheet',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255)),
                ('run', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, related_name='run', to='db.run')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('strand', models.CharField(max_length=1)),
                ('sequence', models.TextField(blank=True, null=True)),
                ('end_coord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                related_name='sequence_ends', to='db.genomiccoordinate')),
                ('start_coord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                  related_name='sequence_starts', to='db.genomiccoordinate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('refseq_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('canonical', models.BooleanField()),
                ('gene', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.gene')),
                ('sequence', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.sequence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantReport',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('qual', models.IntegerField()),
                ('filter_pass', models.BooleanField(null=True)),
                ('variant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VCF',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('path', models.TextField()),
                ('file', models.FileField(default=None, null=True, upload_to='')),
                ('run', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.run')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantReportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('value', models.CharField(max_length=255)),
                ('variant_report', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.variantreport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantReportFilter',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('value', models.CharField(max_length=255)),
                ('variant_report', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.variantreport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='variantreport',
            name='vcf',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='db.vcf'),
        ),
        migrations.CreateModel(
            name='VariantCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('coordinate', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.genomiccoordinate')),
                ('variant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranscriptVariant',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('hgvs_c', models.TextField()),
                ('hgvs_p', models.TextField()),
                ('hgvs_g', models.TextField()),
                ('transcript', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.transcript')),
                ('variant', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleVCF',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.sample')),
                ('vcf', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.vcf')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleVariant',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.sample')),
                ('variant', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleTranscriptVariant',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('selected', models.BooleanField()),
                ('effect', models.CharField(max_length=255)),
                ('sample_variant', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.samplevariant')),
                ('transcript', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.transcript')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SamplesheetSample',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, related_name='sample', to='db.sample')),
                ('samplesheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                  related_name='samplesheet', to='db.samplesheet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleBAM',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('bam', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.bam')),
                ('sample', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='bams',
            field=models.ManyToManyField(through='db.SampleBAM', to='db.BAM'),
        ),
        migrations.AddField(
            model_name='sample',
            name='samplesheets',
            field=models.ManyToManyField(
                through='db.SamplesheetSample', to='db.Samplesheet'),
        ),
        migrations.AddField(
            model_name='sample',
            name='vcfs',
            field=models.ManyToManyField(through='db.SampleVCF', to='db.VCF'),
        ),
        migrations.CreateModel(
            name='GeneReport',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('coverage_info', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.coverageinfo')),
                ('excel_report', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.excelreport')),
                ('gene', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.gene')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneAlias',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gene', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.gene')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExonReport',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('coverage_info', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='db.coverageinfo')),
                ('excel_report', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.excelreport')),
                ('exon', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='db.exon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exon',
            name='sequence',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='db.sequence'),
        ),
        migrations.AddField(
            model_name='exon',
            name='transcript',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='db.transcript'),
        ),
        migrations.AddField(
            model_name='excelreport',
            name='run',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='db.run'),
        ),
        migrations.AddField(
            model_name='excelreport',
            name='sample',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='db.sample'),
        ),
        migrations.AddField(
            model_name='bam',
            name='run',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='db.run'),
        ),
    ]
