# Generated by Django 3.1.6 on 2021-03-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('cov_10x', models.IntegerField()),
                ('cov_20x', models.IntegerField()),
                ('cov_30x', models.IntegerField()),
                ('cov_40x', models.IntegerField()),
                ('cov_50x', models.IntegerField()),
                ('cov_100x', models.IntegerField()),
                ('cov_min', models.IntegerField()),
                ('cov_max', models.IntegerField()),
                ('cov_mean', models.FloatField()),
                ('cov_region', models.IntegerField()),
                ('pct_10x', models.IntegerField()),
                ('pct_20x', models.IntegerField()),
                ('pct_30x', models.IntegerField()),
                ('pct_40x', models.IntegerField()),
                ('pct_50x', models.IntegerField()),
                ('pct_100x', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('path', models.TextField()),
                ('file', models.FileField(default=None, null=True, upload_to='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.run')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=4)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.sequence')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.transcript')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.genomiccoordinate')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('coverage_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.coverageinfo')),
                ('excel_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.excelreport')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.gene')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExonReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('coverage_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.coverageinfo')),
                ('excel_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.excelreport')),
                ('exon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.exon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
