# Generated by Django 3.1.6 on 2021-03-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20210325_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sample',
            name='index',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='index2',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_id',
        ),
        migrations.RemoveField(
            model_name='samplesheet',
            name='run',
        ),
        migrations.AddField(
            model_name='run',
            name='samplesheet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.samplesheet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplesheetsample',
            name='gene_key',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplesheetsample',
            name='index',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplesheetsample',
            name='index2',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplesheetsample',
            name='sample_identifier',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantreport',
            name='depth',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='exon',
            name='sequence',
        ),
        migrations.CreateModel(
            name='ExonSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('exon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.exon')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.sequence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exon',
            name='sequence',
            field=models.ManyToManyField(through='db.ExonSequence', to='db.Sequence'),
        ),
    ]
