# Generated by Django 3.1.6 on 2021-04-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210401_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelreport',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.run'),
        ),
        migrations.AlterField(
            model_name='samplesheet',
            name='latest_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest', to='db.run'),
        ),
        migrations.AlterField(
            model_name='vcf',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.run'),
        ),
    ]
