# Generated by Django 3.1.6 on 2021-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210413_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletranscriptvariant',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
