# Generated by Django 3.1.6 on 2021-04-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_sampletranscriptvariant_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='db.patient'),
            preserve_default=False,
        ),
    ]
