# Generated by Django 3.1.6 on 2021-04-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210427_1240'),
        ('db', '0008_auto_20210422_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineversion',
            name='default_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.filter'),
        ),
        migrations.AlterField(
            model_name='bam',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.run'),
        ),
        migrations.AlterField(
            model_name='vcf',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.run'),
        ),
    ]
