# Generated by Django 3.1.6 on 2021-05-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20210507_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesheetsample',
            name='index2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
