# Generated by Django 3.1.6 on 2021-05-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20210510_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelreport',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.run'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('ref', 'alt')},
        ),
    ]
