# Generated by Django 3.1.6 on 2021-05-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20210513_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='sequence',
        ),
    ]
