# Generated by Django 3.1.6 on 2021-05-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_section_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='slug',
        ),
        migrations.AddField(
            model_name='sample',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='db.section'),
        ),
    ]
