# Generated by Django 3.1.6 on 2021-05-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20210512_1229'),
        ('db', '0012_auto_20210510_0954'),
    ]

    operations = [
    ]
