# Generated by Django 3.1.6 on 2021-05-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_merge_20210513_1155'),
        ('db', '0015_auto_20210521_1105'),
    ]

    operations = [
    ]
