# Generated by Django 3.1.6 on 2021-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20210521_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='alt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='ref',
            field=models.TextField(),
        ),
    ]
