# Generated by Django 3.1.6 on 2021-05-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_auto_20210524_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptvariant',
            name='hgvs_g',
        ),
    ]
