# Generated by Django 3.1.6 on 2021-05-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_remove_transcriptvariant_hgvs_g'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampletranscriptvariant',
            old_name='effect',
            new_name='consequence',
        ),
        migrations.AddField(
            model_name='run',
            name='config_file',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampletranscriptvariant',
            name='impact',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
