# Generated by Django 3.1.6 on 2021-05-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20210525_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantreport',
            unique_together=set(),
        ),
    ]
