# Generated by Django 3.1.6 on 2021-05-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_auto_20210526_1603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exonsequence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exonsequence',
            name='exon',
        ),
        migrations.RemoveField(
            model_name='exonsequence',
            name='sequence',
        ),
        migrations.AlterUniqueTogether(
            name='genomiccoordinate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genomiccoordinate',
            name='genome_build',
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='end_coord',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='start_coord',
        ),
        migrations.AlterUniqueTogether(
            name='variantcoordinate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variantcoordinate',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='variantcoordinate',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='exon',
            name='sequence',
        ),
        migrations.AddField(
            model_name='exon',
            name='alt_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.exon'),
        ),
        migrations.AddField(
            model_name='exon',
            name='chrom',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exon',
            name='end_pos',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exon',
            name='genome_build',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.genomebuild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exon',
            name='start_pos',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='alt_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.variant'),
        ),
        migrations.AddField(
            model_name='variant',
            name='chrom',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='genome_build',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.genomebuild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='pos',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('chrom', 'pos', 'ref', 'alt', 'genome_build')},
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['chrom', 'pos'], name='db_variant_chrom_aee9e1_idx'),
        ),
        migrations.DeleteModel(
            name='ExonSequence',
        ),
        migrations.DeleteModel(
            name='GenomicCoordinate',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.DeleteModel(
            name='VariantCoordinate',
        ),
    ]
