# Generated by Django 3.1.6 on 2021-05-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_auto_20210527_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='exon',
            name='strand',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='exon',
            index=models.Index(fields=['chrom', 'start_pos'], name='db_exon_chrom_c884ac_idx'),
        ),
    ]
