# Generated by Django 3.1.6 on 2021-05-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_auto_20210527_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exon',
            name='alt_build',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.exon'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='alt_build',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.variant'),
        ),
    ]
