# Generated by Django 3.1.6 on 2021-05-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_auto_20210527_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomebuild',
            name='path',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genomebuild',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
