# Generated by Django 3.1.6 on 2021-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_auto_20210527_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exon',
            name='chrom',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='exon',
            name='end_pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exon',
            name='start_pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exon',
            name='strand',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
