# Generated by Django 3.1.6 on 2021-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20210528_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantreport',
            name='qual',
            field=models.IntegerField(null=True),
        ),
    ]
