# Generated by Django 3.1.6 on 2021-06-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_exonreport_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exonreport',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
