# Generated by Django 3.1.6 on 2021-06-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_auto_20210625_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='genereport',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genereport',
            name='transcript',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db.transcript'),
        ),
    ]
