# Generated by Django 3.1.6 on 2021-06-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_auto_20210625_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genereport',
            unique_together={('excel_report', 'gene', 'transcript', 'tag')},
        ),
    ]
