# Generated by Django 3.1.6 on 2021-09-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_auto_20210625_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exonreport',
            name='cov_100x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='cov_10x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='cov_20x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='cov_30x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='cov_40x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='cov_50x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='pct_100x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='pct_10x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='pct_20x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='pct_30x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='pct_40x',
        ),
        migrations.RemoveField(
            model_name='exonreport',
            name='pct_50x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='cov_100x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='cov_10x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='cov_20x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='cov_30x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='cov_40x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='cov_50x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='pct_100x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='pct_10x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='pct_20x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='pct_30x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='pct_40x',
        ),
        migrations.RemoveField(
            model_name='genereport',
            name='pct_50x',
        ),
        migrations.CreateModel(
            name='GeneCoverageThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('threshold', models.IntegerField()),
                ('coverage', models.IntegerField()),
                ('pct_above_threshold', models.IntegerField()),
                ('gene_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.genereport')),
            ],
            options={
                'unique_together': {('gene_report', 'threshold')},
            },
        ),
        migrations.CreateModel(
            name='ExonCoverageThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('threshold', models.IntegerField()),
                ('coverage', models.IntegerField()),
                ('pct_above_threshold', models.IntegerField()),
                ('exon_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.exonreport')),
            ],
            options={
                'unique_together': {('exon_report', 'threshold')},
            },
        ),
    ]
