# Generated by Django 3.1.6 on 2021-08-13 11:18

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_auto_20210625_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineversion',
            name='classification_options',
            field=models.JSONField(default=db.models.PipelineVersion.default_classification_options),
        ),
    ]
