# Generated by Django 3.1.6 on 2021-04-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210413_1015'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sample_transcript_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='db.sampletranscriptvariant'),
            preserve_default=False,
        ),
    ]
