# Generated by Django 3.1.6 on 2021-04-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_document_sample_transcript_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='document',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
