# Generated by Django 3.1.6 on 2021-04-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210413_1015'),
        ('web', '0003_auto_20210413_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('classification', models.IntegerField(choices=[(0, 'Unclassfied'), (1, 'Pathogenic'), (2, 'Likely Pathogenic'), (3, 'Vus'), (4, 'Likely Benign'), (5, 'Benign')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('sample_transcript_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='db.sampletranscriptvariant')),
            ],
        ),
    ]
