# Generated by Django 3.1.6 on 2021-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Unclassified'), (1, 'Pathogenic'), (2, 'Likely Pathogenic'), (3, 'Vus'), (4, 'Likely Benign'), (5, 'Benign')], default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
