# Generated by Django 3.1.6 on 2021-04-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20210422_1243'),
        ('web', '0005_auto_20210420_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genekey', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('vcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.vcf')),
            ],
        ),
        migrations.CreateModel(
            name='FilterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('filter_type', models.CharField(choices=[('__isnull', 'Is Defined'), ('__iexact', 'Is'), ('__icontains', 'Contains'), ('__lt', 'Less Than'), ('__gt', 'Greater Than'), ('__lte', 'Less Than Or Equal To'), ('__gte', 'Greater Than Or Equal To')], default='__isnull', max_length=15)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.filter')),
            ],
        ),
    ]
