# Generated by Django 3.1.6 on 2021-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_filter_filteritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='genekey',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='vcf',
        ),
        migrations.AddField(
            model_name='filter',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='filter_type',
            field=models.CharField(choices=[('__iexact', 'is'), ('__ne', 'is not'), ('__icontains', 'contains'), ('__lt', '<'), ('__gt', '>'), ('__lte', '≤'), ('__gte', '≥')], default='__iexact', max_length=15),
        ),
    ]
