# Generated by Django 3.1.6 on 2021-04-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210427_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='name',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
