# Generated by Django 3.1.6 on 2021-04-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_filter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='match',
            field=models.CharField(choices=[('all', 'Match all of the above rules'), ('any', 'Match any of the above rules')], default='all', max_length=15),
        ),
        migrations.AlterField(
            model_name='filteritem',
            name='filter_type',
            field=models.CharField(choices=[('__exact', 'is'), ('__ne', 'is not'), ('__icontains', 'contains'), ('__lt', '<'), ('__gt', '>'), ('__lte', '≤'), ('__gte', '≥')], default='__exact', max_length=15),
        ),
    ]
