# Generated by Django 3.1.6 on 2021-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210429_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteritem',
            name='filter_type',
            field=models.CharField(choices=[('__iexact', 'is'), ('__ne', 'is not'), ('__icontains', 'contains'), ('__lt', '<'), ('__gt', '>'), ('__lte', '≤'), ('__gte', '≥')], default='__iexact', max_length=15),
        ),
    ]
