# Generated by Django 3.1.6 on 2021-05-19 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210430_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteritem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filteritem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
