# Generated by Django 3.1.6 on 2021-06-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_auto_20210527_1152'),
        ('web', '0013_document_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=2000)),
                ('recommendations', models.CharField(blank=True, max_length=2000)),
                ('data', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='db.run')),
                ('samplesheetsample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='db.samplesheetsample')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
