# Generated by Django 3.1.6 on 2021-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Unclassified'), (1, 'Benign'), (2, 'Likely Benign'), (3, 'Vus'), (4, 'Likely Pathogenic'), (5, 'Pathogenic')], default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
