# Generated by Django 3.1.6 on 2021-07-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210624_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteritem',
            name='or_next',
            field=models.BooleanField(default=False),
        ),
    ]
