# Generated by Django 3.1.6 on 2021-07-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_filteritem_or_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='match',
        ),
    ]
