# Generated by Django 3.1.6 on 2021-07-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_filter_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filteritem',
            options={'ordering': ['id']},
        ),
    ]
