# Generated by Django 3.1.6 on 2021-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20210728_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='classification',
            field=models.IntegerField(default=0),
        ),
    ]
