# Generated by Django 3.1.6 on 2021-08-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_pipelineversion_classification_options'),
        ('web', '0019_auto_20210813_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sample_transcript_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='db.sampletranscriptvariant'),
        ),
    ]
