# Generated by Django 3.1.6 on 2021-05-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20210512_1229'),
        ('accounts', '0004_userfilter_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='db.section'),
        ),
    ]
